// 3-qwik/src/components/episode-action-area.tsx
import { Episode } from "../model/episode";
import { component$, useStore } from "@builder.io/qwik";
import { EditEpisode } from "~/components/episode-edit";
import { Button } from "~/components/button";

export type EpisodeActionArea = {
  episode: Episode;
};

export const EpisodeActionArea = component$(
  ({ episode }: EpisodeActionArea) => {
    const store = useStore({ edit: false });

    if (store.edit) {
      return (
        <div>
          <EditEpisode
            content={episode.contentMd}
            cancel$={() => {
              store.edit = false;
            }}
            save$={() => void true}
          ></EditEpisode>
        </div>
      );
    } else {
      return (
        <div className="flex justify-center my-4 gap-2">
          <Button>Full Episode</Button>
          <Button>Comments</Button>
          <Button
            onClick$={() => {
              store.edit = true;
            }}
          >
            Edit
          </Button>
        </div>
      );
    }
  }
);

// 1-nextjs/components/EpisodeActionArea.tsx
import { Episode } from '../model/episode';
import Button from './Button';
import { useState } from 'react';
import dynamic from 'next/dynamic';

const EditEpisodeWrapper = dynamic(() => import('./EpisodeEdit'), {
  ssr: false,
});

export type EpisodeActionArea = {
  episode: Episode;
};

export default function EpisodeActionArea({ episode }: EpisodeActionArea) {
  const [edit, setEdit] = useState(false);

  if (edit) {
    return (
      <div>
        <EditEpisodeWrapper
          content={episode.contentMd}
          cancel={() => setEdit(false)}
          save={() => void true}
        ></EditEpisodeWrapper>
      </div>
    );
  } else {
    return (
      <div className="flex justify-center my-4 gap-2">
        <Button label="Full Episode" />
        <Button label="Comments" />
        <Button label="Edit" onClick={() => setEdit(!edit)} />
      </div>
    );
  }
}
