// 1-nextjs/components/Button.tsx
export type ButtonProps = {
  label: string;
  onClick?: () => void;
};

export default function Button({ label, onClick }: ButtonProps) {
  return (
    <button
      onClick={onClick}
      className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
    >
      {label}
    </button>
  );
}

// qwik/src/components/button.tsx
import { component$, PropFunction, Slot } from "@builder.io/qwik";

export type ButtonProps = {
  onClick$?: PropFunction<() => void>;
};

export const Button = component$((props: ButtonProps) => {
  return (
    <button
      className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      onClick$={async () => {
        if (props.onClick$) {
          await props.onClick$();
        }
      }}
    >
      <Slot />
    </button>
  );
});
