// 3-qwik/src/components/episode-edit.tsx
import { component$, PropFunction } from "@builder.io/qwik";
import { Button } from "~/components/button";

export type EditEpisodeProps = {
  content: string;
  save$: PropFunction<(content: string) => void>;
  cancel$: PropFunction<() => void>;
};

export const EditEpisode = component$((props: EditEpisodeProps) => {
  return (
    <div className="mx-4">
      <textarea
        value={props.content}
        className="w-full rounded px-4 h-64"
      ></textarea>
      <div className="flex justify-evenly my-4">
        <Button
          onClick$={async () => {
            if (props.cancel$) {
              await props.cancel$();
            }
          }}
        >
          Cancel
        </Button>
        <Button
          onClick$={async () => {
            if (props.save$) {
              await props.save$(props.content);
            }
          }}
        >
          Save
        </Button>
      </div>
    </div>
  );
});

// nextjs/components/EpisodeEdit.tsx
import { useState } from 'react';
import 'react-quill/dist/quill.snow.css';
import Button from './Button';

export type EditEpisodeProps = {
  content: string;
  save: (content: string) => void;
  cancel: () => void;
};

export default function EditEpisode({
  content,
  save,
  cancel,
}: EditEpisodeProps) {
  const [value, setValue] = useState(content);
  return (
    <div className="mx-4">
      <textarea
        value={value}
        onChange={(v) => setValue(v.target.value)}
        className="w-full rounded px-4 h-64"
      ></textarea>
      <div className="flex justify-evenly my-4">
        <Button onClick={() => cancel()} label="Cancel"></Button>
        <Button label="Save" onClick={() => save(value)}></Button>
      </div>
    </div>
  );
}
